#!/usr/bin/env python3
"""
Regenerate firmware/src/utils/crypto/Bip39Wordlist.cpp from the canonical
BIP-39 English wordlist published in github.com/bitcoin/bips.

Run when bumping the wordlist or recovering the file from scratch:

    python3 scripts/gen_bip39_wordlist.py

Validates: exactly 2048 words, ASCII-only, lowercase, sorted lex.
"""

import hashlib
import sys
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/english.txt"
OUT = Path(__file__).resolve().parent.parent / "firmware/src/utils/crypto/Bip39Wordlist.cpp"


def main() -> int:
    print(f"Fetching {URL}")
    raw = urllib.request.urlopen(URL, timeout=30).read().decode("ascii")
    words = [w.strip() for w in raw.splitlines() if w.strip()]

    if len(words) != 2048:
        print(f"ERROR: expected 2048 words, got {len(words)}", file=sys.stderr)
        return 1
    if any(not w.isascii() or not w.islower() for w in words):
        print("ERROR: non-ASCII or uppercase word found", file=sys.stderr)
        return 1
    if sorted(words) != words:
        print("ERROR: wordlist is not lexicographically sorted", file=sys.stderr)
        return 1

    digest = hashlib.sha256(("\n".join(words) + "\n").encode("ascii")).hexdigest()
    print(f"Words: {len(words)}, sha256: {digest}")

    lines = [
        "// Generated by scripts/gen_bip39_wordlist.py - do not edit by hand.",
        "// Source: github.com/bitcoin/bips/bip-0039/english.txt (BIP-39 English).",
        f"// SHA-256 (joined with \\n, trailing \\n): {digest}",
        "",
        "#include \"Bip39Wordlist.h\"",
        "",
        "namespace unigeek { namespace crypto {",
        "",
        "const char* const kBip39EnglishWordlist[2048] = {",
    ]
    for i in range(0, 2048, 4):
        chunk = ", ".join(f"\"{w}\"" for w in words[i:i + 4])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append("")
    lines.append("}}  // namespace unigeek::crypto")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
