#pragma once

namespace unigeek {
namespace crypto {

// Canonical BIP-39 English wordlist (2048 entries, lex-sorted).
// Generated by scripts/gen_bip39_wordlist.py. Do not edit by hand.
extern const char* const kBip39EnglishWordlist[2048];

}  // namespace crypto
}  // namespace unigeek
